### ISSUE TITLE
CI/CD pipelines

### ISSUE THREAD

**Issue by Elaniobro** [newyorkmyc/keys-typeahead#12]
It would be nice if we can make this SPA use CI/CD to re-build the `.json` files whenever we merge an updated `.csv` file into the codebase.

- [ ] on merge validate the code
- [ ] use an action job to lint the code
- [ ] use an action job to run the `.py` script to build a new `.json`
- [ ] use an action job to scp the SPA to our server
- [ ] use github secrets to store the environment variables

**Comment by mrozanoff** [comment]
I pushed some files to the associated branch, how do you test actions?

**Comment by Elaniobro** [comment]
The actions are triggered when you tell them to run. Here you are telling the action  when to be triggered, which is on the push of code to the main branch. 
```yml
# Run this workflow on a push to main or on a schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight; adjust as needed
```

You could update it to test and trigger on push to your branch changing this [line 7](https://github.com/newyorkmyc/keys-typeahead/blob/12-cicd-pipelines/.github/workflows/update_json.yml#L7) to read your working branch name.
```yml
on:
  push:
    branches:
      - 12-cicd-pipelines
```

I also do not think we want to make use of a cron job, no need for it run if there isn't any changes. The trigger _should_ be enough.

And your commit line is missing the commitlint syntax on [line 43](https://github.com/newyorkmyc/keys-typeahead/blob/12-cicd-pipelines/.github/workflows/update_json.yml#L43)

Lastly I think you may need to create a TOKEN, which we will need to add to the repo secrets. Been awhile so can't recall specifically if one is needed for the commiting of the file or not in the workflow.
