### ISSUE TITLE
Add a deploy step/job or new action

### ISSUE THREAD

**Issue by Elaniobro** [newyorkmyc/keys-typeahead#16]
As part of the CI/CD process, we should have the ability for github to automatically pkg up and deploy updates to the website.

We will likely need to tar/untar the contents vis ssh/scp

Here is an example of how we _may_ achieve something similar. The below is just an outline for a windows server, and we will want to modify it to work with our server (linux) and the build `.json` job you already completed.

We will need to add a few secrets to github to be used

- [x] ssh username
- [x] ssh password
- [x] server host
- [ ] ....

```yml
name: CI/CD Pipeline - Build & Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      # Pull Request Closed event for branches matching 'main'
      - 'main'

# Define global variable scoped to entire workflow
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  Lint-Test-and-Validate:
    name: Lint, Test and Validate
    # If check for if pull request event was merged
    if: github.event.pull_request.merged
    runs-on: [ self-hosted, linux, x64 ]
    steps:
      # Get the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node 18.x
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Install pkg manager pnpm 
      # likely want to use NPM
      - name: Install pnpm
        uses: actions/setup-pnpm@v2.0.0
        id: pnpm-install
        with:
          version: 7
          run_install: false

      # Get the cached version of pnpm
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Setup pnpm cache
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install pkg dependencies
      - name: Install package.json dependencies
        run: pnpm install

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      # Run super-linter action with the below variables
      - name: Super-Linter
        uses: actions/super-linter@v4.9.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          CSS_FILE_NAME: stylelint.config.js
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          TYPESCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_BASH_EXEC: false
          VALIDATE_BASH: false
          VALIDATE_CSS: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_POWERSHELL: false
          VALIDATE_SHELL_SHFMT: false
          # Add a validate for python?


  # This workflow contains a single job called "build"
  Build:
    # Specify the environment to use branch rules
    environment: PROD_APPROVAL
    if: github.event.pull_request.merged

    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64]

    # describe what checks are required for this build to proceed
    needs: Lint-Test-and-Validate

    # Env variables to be used in build step
    env:
      API_URL: 'www.example.com'
      API_KEY: ${{ secrets.API_KEY_PROD }}
      ROUTER_BASE: /"$REPO_NAME"
      NUXT_ENV: 'production' # not using Nuxt or React

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under "$GITHUB_WORKSPACE", so your job can access it
       # Get the code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install Node 18.x
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # Install pkg manager pnpm
      - name: Install pnpm
        uses: actions/setup-pnpm@v2.0.0
        id: pnpm-install
        with:
          version: 7
          run_install: false

      # Get the cached version of pnpm
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # Setup pnpm cache
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install pkg dependencies
      - name: Install package.json dependencies
        run: pnpm install

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      # Run command to generate the build
      - name: 'Generate Static Resources for Test environment'
        run: NUXT_ENV='${{ env.NUXT_ENV }}' ROUTER_BASE=${{ env.ROUTER_BASE }} pnpm generate

      # Tar and Gzip the nuxt build .output/public dir
      - name: Tar & Gzip build output
        run: tar -C "$GITHUB_WORKSPACE"/dist -czvf ${{ github.head_ref }}.tar.gz .

      # Upload artifact for persistence across steps/jobs
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.head_ref }}.artifact
          path: ${{ github.head_ref }}.tar.gz

  Deploy-to-NYMS:
    name: Deploy build to NYMS_HOST
    runs-on: [ self-hosted, linux, x64 ]
    needs: [ Build, Lint-Test-and-Validate ]

    steps:
      # Uses uploaded artifact from previous job
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.head_ref }}.artifact

      # Verify the tar file exists before moving on
      - name: Verify ${{ github.head_ref }}.tar.gz exists
        run: ls -l ${{ github.head_ref }}.tar.gz

      # Secure copy the tar file to the remote server
      - name: Secure copy ${{ github.head_ref }}.tar.gz to NYMS_HOST
        run: scp ${{ github.head_ref }}.tar.gz ${{ secrets.SSH_USERNAME }}@${{ secrets.NYMS_HOST}}:C:/_apps/builds/${{ github.head_ref }}.tar.gz

      # SSH into remote server, see if directory exists make one if not, extract the tar file and check if a tar file exists, delete if so
      - name: SSH and untar ${{ github.head_ref }}.tar.gz on NYMS_HOST
        run: >
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.NYMS_HOST}} << "EOF"
            if (!(Test-Path C:\_apps\${{ github.event.repository.name }})) { mkdir C:\_apps\${{ github.event.repository.name }} }
            cd C:\_apps\${{ github.event.repository.name }}
            if (!(Test-Path ${{ github.head_ref }})) { mkdir ${{ github.head_ref }} }
            tar -xzvf C:/_apps/builds/${{ github.head_ref }}.tar.gz -C C:\_apps\${{ github.event.repository.name }}
            if (Test-Path C:/_apps/builds/${{ github.head_ref }}.tar.gz) { del C:/_apps/builds/${{ github.head_ref }}.tar.gz }
          EOF
```
