### ISSUE TITLE
Fix Action: Update Fungi Taxonomy JSON

### ISSUE THREAD

**Issue by newyorkmyc** [newyorkmyc/keys-typeahead#23]
There are branch protection rules on this repo to prevent errant code from going into production.

The current pipeline does now allow for the `fungi_taxonmy.json` to be updated and commited b/c of the rules. There is a PAT that could be used in the pipeline to bypass this. 

Here is the error:
```bash
[main adeab73] ci: Update fungi_taxonomy.json
 1 file changed, 1882 insertions(+), 1831 deletions(-)
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: Review all repository rules at https://github.com/newyorkmyc/keys-typeahead/rules?ref=refs%2Fheads%2Fmain        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
To https://github.com/newyorkmyc/keys-typeahead
 ! [remote rejected] main -> main (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/newyorkmyc/keys-typeahead'
Error: Process completed with exit code 1.
```

We also do not want this to run on push but rather on cron.

```yml
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  ```
  
  should be:
 
  ```yml
  on:
  schedule:
    - cron: '0 0 1 * *'
```
